### PR TITLE
Change name, license and packaging

### PR DESCRIPTION
**Pull request by mcalmer**
As discussed in the PAYG meeting we wanted to make the naming more neutral.
The storage scripts work also on VM images and in a DC environment.
As we may plan to move them to uyuni-tools, we wanted to change the license to ~GPL 2.0 only~ GPL 3.0 only.
This PR change also the packaging and does a missing cleanup.

This PR is for discussion

### CODE REVIEW

**Comment by jgleissner** [comment]
This looks good to me, thanks!

**Comment by mcalmer** [comment]
JFYI: Abid will clarify if GPLv3 or later can be used. We would like to move this into our own git as standalone package and than the license does not need to match to any existing package. So maybe I will remove the license change.

**Comment by mcalmer** [comment]
About the License change: We stay with GPLv3, but remove the "or later" part.

**Review by jgleissner — APPROVED** [review]
LGTM

**Pull request merged**
